schema_version = "1.0.0"

id = "quickexporter"
version = "1.0.0"
name = "Quick Exporter"
tagline = "Create, manage, and export custom model packages"
maintainer = "Tony Coculuzzi - Wilder Games"
type = "add-on"
website = "https://github.com/wildergames/blender-quick-exporter"
tags = ["Import-Export", "Pipeline", "Mesh"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

copyright = [
  "2018-2026 Tony Coculuzzi",
  "2018-2026 Wilder Games",
]

[permissions]
files = "Import/export FBX and other model file types from/to disk"

[build]
paths_exclude_pattern = [
  "__pycache__/",
  ".git",
  "*.zip",
  "screenshots/"
]